language: go

sudo: required
dist: trusty

git:
  depth: 3

before_install:
  - sudo apt-get update -qq
  - go get google.golang.org/grpc
  - go install $TRAVIS_BUILD_DIR/lib/poohbear

script: make build
