language: go

sudo: required
dist: trusty

git:
  depth: 3

cache:
  directories:
  - $GOPATH/src
  - $GOPATH/pkg

before_install:
  - sudo apt-get update -qq
  - go get google.golang.org/grpc
  - go get github.com/jcelliott/turnpike
  - go get github.com/boltdb/bolt/...
  - go get github.com/k0kubun/pp
  - go get -u go.uber.org/zap

script: make build
