# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade.proto',
  package='main',
  syntax='proto3',
  serialized_pb=_b('\n\x0btrade.proto\x12\x04main\"U\n\x05Trade\x12\x0c\n\x04pair\x18\x01 \x01(\t\x12\x0c\n\x04rate\x18\x02 \x01(\x02\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\r\n\x05total\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"J\n\nTradeBlock\x12\x0c\n\x04pair\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x1b\n\x06trades\x18\x03 \x03(\x0b\x32\x0b.main.Trade\"A\n\x0fTradeBlockRange\x12\x0c\n\x04pair\x18\x01 \x01(\t\x12 \n\x06trades\x18\x02 \x03(\x0b\x32\x10.main.TradeBlock\"G\n\tDateRange\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0c\n\x04pair\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\t\x12\x0b\n\x03\x65nd\x18\x04 \x01(\t2G\n\nTradeRange\x12\x39\n\rGetTradeRange\x12\x0f.main.DateRange\x1a\x15.main.TradeBlockRange\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRADE = _descriptor.Descriptor(
  name='Trade',
  full_name='main.Trade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair', full_name='main.Trade.pair', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='main.Trade.rate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='main.Trade.amount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total', full_name='main.Trade.total', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='main.Trade.timestamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=106,
)


_TRADEBLOCK = _descriptor.Descriptor(
  name='TradeBlock',
  full_name='main.TradeBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair', full_name='main.TradeBlock.pair', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='main.TradeBlock.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trades', full_name='main.TradeBlock.trades', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=182,
)


_TRADEBLOCKRANGE = _descriptor.Descriptor(
  name='TradeBlockRange',
  full_name='main.TradeBlockRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair', full_name='main.TradeBlockRange.pair', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trades', full_name='main.TradeBlockRange.trades', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=249,
)


_DATERANGE = _descriptor.Descriptor(
  name='DateRange',
  full_name='main.DateRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='main.DateRange.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pair', full_name='main.DateRange.pair', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='main.DateRange.start', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='main.DateRange.end', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=322,
)

_TRADEBLOCK.fields_by_name['trades'].message_type = _TRADE
_TRADEBLOCKRANGE.fields_by_name['trades'].message_type = _TRADEBLOCK
DESCRIPTOR.message_types_by_name['Trade'] = _TRADE
DESCRIPTOR.message_types_by_name['TradeBlock'] = _TRADEBLOCK
DESCRIPTOR.message_types_by_name['TradeBlockRange'] = _TRADEBLOCKRANGE
DESCRIPTOR.message_types_by_name['DateRange'] = _DATERANGE

Trade = _reflection.GeneratedProtocolMessageType('Trade', (_message.Message,), dict(
  DESCRIPTOR = _TRADE,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:main.Trade)
  ))
_sym_db.RegisterMessage(Trade)

TradeBlock = _reflection.GeneratedProtocolMessageType('TradeBlock', (_message.Message,), dict(
  DESCRIPTOR = _TRADEBLOCK,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:main.TradeBlock)
  ))
_sym_db.RegisterMessage(TradeBlock)

TradeBlockRange = _reflection.GeneratedProtocolMessageType('TradeBlockRange', (_message.Message,), dict(
  DESCRIPTOR = _TRADEBLOCKRANGE,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:main.TradeBlockRange)
  ))
_sym_db.RegisterMessage(TradeBlockRange)

DateRange = _reflection.GeneratedProtocolMessageType('DateRange', (_message.Message,), dict(
  DESCRIPTOR = _DATERANGE,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:main.DateRange)
  ))
_sym_db.RegisterMessage(DateRange)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class TradeRangeStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetTradeRange = channel.unary_unary(
          '/main.TradeRange/GetTradeRange',
          request_serializer=DateRange.SerializeToString,
          response_deserializer=TradeBlockRange.FromString,
          )


  class TradeRangeServicer(object):

    def GetTradeRange(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_TradeRangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetTradeRange': grpc.unary_unary_rpc_method_handler(
            servicer.GetTradeRange,
            request_deserializer=DateRange.FromString,
            response_serializer=TradeBlockRange.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'main.TradeRange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaTradeRangeServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetTradeRange(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaTradeRangeStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetTradeRange(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetTradeRange.future = None


  def beta_create_TradeRange_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('main.TradeRange', 'GetTradeRange'): DateRange.FromString,
    }
    response_serializers = {
      ('main.TradeRange', 'GetTradeRange'): TradeBlockRange.SerializeToString,
    }
    method_implementations = {
      ('main.TradeRange', 'GetTradeRange'): face_utilities.unary_unary_inline(servicer.GetTradeRange),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_TradeRange_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('main.TradeRange', 'GetTradeRange'): DateRange.SerializeToString,
    }
    response_deserializers = {
      ('main.TradeRange', 'GetTradeRange'): TradeBlockRange.FromString,
    }
    cardinalities = {
      'GetTradeRange': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'main.TradeRange', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
